// ADMIN
export const ADD_PRODUCT_START = 'ADD_PRODUCT_START';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';

// AUTH
export const AUTH_START = 'SIGN_UP_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// PRODUCTS
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const FETCH_SINGLE_PRODUCT_START = 'FETCH_SINGLE_PRODUCT_START';
export const FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_SINGLE_PRODUCT_SUCCESS';
export const FETCH_SINGLE_PRODUCT_FAIL = 'FETCH_SINGLE_PRODUCT_FAIL';

// CART
export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const REMOVE_FROM_CART_START = 'REMOVE_FROM_CART_START';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';

export const REMOVE_FULL_ITEM_FROM_CART_START = 'REMOVE_FULL_ITEM_FROM_CART_START';
export const REMOVE_FULL_ITEM_FROM_CART_SUCCESS = 'REMOVE_FULL_ITEM_FROM_CART_SUCCESS';
export const REMOVE_FULL_ITEM_FROM_CART_FAIL = 'REMOVE_FULL_ITEM_FROM_CART_FAIL';

export const FETCH_CART_START = 'FETCH_CART_START';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL';

export const LOAD_SHALLOW_CART_START = 'LOAD_SHALLOW_CART_START';
export const LOAD_SHALLOW_CART_SUCCESS = 'LOAD_SHALLOW_CART_SUCCESS';
export const LOAD_SHALLOW_CART_FAIL = 'LOAD_SHALLOW_CART_FAIL';

export const LOAD_CART_START = 'LOAD_CART_START';
export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS';
export const LOAD_CART_FAIL = 'LOAD_CART_FAIL';

export const CLEAR_CART_START = 'CLEAR_CART_START';
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';
export const CLEAR_CART_FAIL = 'CLEAR_CART_FAIL';

export const CLEAR_ADDED_PRODUCT = 'CLEAR_ADDED_PRODUCT';

// WISHLIST

export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAIL = 'ADD_WISHLIST_FAIL';

export const REMOVE_WISHLIST_SUCCESS = 'REMOVE_WISHLIST_SUCCESS';
export const REMOVE_WISHLIST_FAIL = 'REMOVE_WISHLIST_FAIL';

export const FETCH_WISHLIST_START = 'FETCH_WISHLIST_START';
export const FETCH_WISHLIST_SUCCESS = 'FETCH_WISHLIST_SUCCESS';
export const FETCH_WISHLIST_FAIL = 'FETCH_WISHLIST_FAIL';
